//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.3.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
// Templates version: 
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace BlazorTests.Server.Entities.HelperClasses
{
	
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	
	/// <summary>Singleton implementation of the FieldInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	/// <remarks>It uses a single instance of an internal class. The access isn't marked with locks as the FieldInfoProviderBase class is threadsafe.</remarks>
	internal static class FieldInfoProviderSingleton
	{
		#region Class Member Declarations
		private static readonly IFieldInfoProvider _providerInstance = new FieldInfoProviderCore();
		#endregion

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static FieldInfoProviderSingleton()
		{
		}

		/// <summary>Gets the singleton instance of the FieldInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IFieldInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the FieldInfoProvider. Used by singleton wrapper.</summary>
	internal class FieldInfoProviderCore : FieldInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="FieldInfoProviderCore"/> class.</summary>
		internal FieldInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitCustomerEntityInfos();
			InitCustomerTypeEntityInfos();

			this.ConstructElementFieldStructures(InheritanceInfoProviderSingleton.GetInstance());
		}

		/// <summary>Inits CustomerEntity's FieldInfo objects</summary>
		private void InitCustomerEntityInfos()
		{
			this.AddFieldIndexEnumForElementName(typeof(CustomerFieldIndex), "CustomerEntity");
			this.AddElementFieldInfo("CustomerEntity", "Id", typeof(System.Int32), true, false, false, false,  (int)CustomerFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("CustomerEntity", "Name", typeof(System.String), false, false, false, false,  (int)CustomerFieldIndex.Name, 255, 0, 0);
			this.AddElementFieldInfo("CustomerEntity", "FirstName", typeof(System.String), false, false, false, false,  (int)CustomerFieldIndex.FirstName, 255, 0, 0);
			this.AddElementFieldInfo("CustomerEntity", "CustomerTypeId", typeof(System.Int32), false, true, false, false,  (int)CustomerFieldIndex.CustomerTypeId, 0, 0, 10);
		}
		/// <summary>Inits CustomerTypeEntity's FieldInfo objects</summary>
		private void InitCustomerTypeEntityInfos()
		{
			this.AddFieldIndexEnumForElementName(typeof(CustomerTypeFieldIndex), "CustomerTypeEntity");
			this.AddElementFieldInfo("CustomerTypeEntity", "Id", typeof(System.Int32), true, false, false, false,  (int)CustomerTypeFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("CustomerTypeEntity", "Text", typeof(System.String), false, false, false, false,  (int)CustomerTypeFieldIndex.Text, 255, 0, 0);
		}
		
	}
}




